# -*- coding: utf-8 -*-
"""PE01_202310907_김민주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194le5QJWWmSejm-ay4VSFNlq6qFq-Azw
"""

def create_graph_from_file(file_path):

    adj_list = {}
    max_node = 0
    try:
        with open(file_path, 'r') as f:
            # 파일 내용을 공백으로 분리하여 정수 리스트로 변환
            edges = list(map(int, f.read().split()))

        for i in range(0, len(edges), 2):
            u, v = edges[i], edges[i+1]
            # 최대 정점 번호 추적
            max_node = max(max_node, u, v)

            # 인접 리스트에 간선 추가 (양방향)
            if u not in adj_list:
                adj_list[u] = []
            if v not in adj_list:
                adj_list[v] = []
            adj_list[u].append(v)
            adj_list[v].append(u)

    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
        return None, 0
    except ValueError:
        print("Error: The file contains non-integer data.")
        return None, 0

    return adj_list, max_node

adj_list, max_node = create_graph_from_file('searchgraph.txt')
if adj_list:
    print(f"Graph created with {len(adj_list)} nodes and max node number {max_node}.")
    print("Example adjacency list entry for node 48:", adj_list.get(48))
else:
    print("Failed to create graph.")

import sys
sys.setrecursionlimit(2000)

# 1.파일 처리 및 그래프 생성 함수
def create_graph_from_file(file_path):
    adj_list = {}
    max_node = 0
    try:
        with open(file_path, 'r') as f:
            edges = list(map(int, f.read().split()))
        for i in range(0, len(edges), 2):
            u, v = edges[i], edges[i+1]
            max_node = max(max_node, u, v)
            if u not in adj_list: adj_list[u] = []
            if v not in adj_list: adj_list[v] = []
            adj_list[u].append(v)
            adj_list[v].append(u)
    except (FileNotFoundError, ValueError) as e:
        print(f"Error reading file {file_path}: {e}")
        return None, 0
    return adj_list, max_node

# 2.DFS 구현 함수들
def dfs_recursive(adj_list, start_node, visited):
    visited.add(start_node)
    print(start_node, end=' ')
    if start_node in adj_list:
        for neighbor in sorted(adj_list[start_node]):
            if neighbor not in visited:
                dfs_recursive(adj_list, neighbor, visited)

def dfs_iterative_1(adj_list, start_node):
    visited = set()
    stack = [start_node]
    while stack:
        u = stack.pop()
        if u not in visited:
            print(u, end=' ')
            visited.add(u)
            if u in adj_list:
                for neighbor in sorted(adj_list[u], reverse=True):
                    if neighbor not in visited:
                        stack.append(neighbor)

def dfs_iterative_2(adj_list, start_node):
    visited = set()
    stack = [start_node]
    while stack:
        u = stack.pop()
        if u in visited:
            continue
        print(u, end=' ')
        visited.add(u)
        if u in adj_list:
            for neighbor in sorted(adj_list[u], reverse=True):
                if neighbor not in visited:
                    stack.append(neighbor)

# 3.테스트 데이터 생성 함수
import random
def generate_test_graph_data(num_nodes, num_edges, filename):
    edges = set()
    while len(edges) < num_edges:
        u = random.randint(1, num_nodes)
        v = random.randint(1, num_nodes)
        if u != v:
            edge = tuple(sorted((u, v)))
            edges.add(edge)
    with open(filename, 'w') as f:
        for u, v in edges:
            f.write(f"{u} {v} ")
    print(f"Generated {filename}")

# 테스트 데이터 생성
new_file_name = 'test_graph_ai.txt'
generate_test_graph_data(num_nodes=50, num_edges=75, filename=new_file_name)

# searchgraph.txt 테스트
adj_list_1, max_node_1 = create_graph_from_file('searchgraph.txt')
if adj_list_1:
    start_node_1 = 48
    if start_node_1 in adj_list_1:
        print("Recursive DFS:")
        visited_1_rec = set()
        dfs_recursive(adj_list_1, start_node_1, visited_1_rec)
        print("\n")

        print("DFS 1:")
        dfs_iterative_1(adj_list_1, start_node_1)
        print("\n")

        print("DFS 2:")
        dfs_iterative_2(adj_list_1, start_node_1)
        print("\n")
    else:
        print(f"Start node {start_node_1} not in graph.")
else:
    print("Skipping searchgraph.txt test.")

print("\n--- Testing with generated test ---")
adj_list_2, max_node_2 = create_graph_from_file(new_file_name)
if adj_list_2:
    start_node_2 = random.choice(list(adj_list_2.keys()))
    print("Recursive DFS:")
    visited_2_rec = set()
    dfs_recursive(adj_list_2, start_node_2, visited_2_rec)
    print("\n")

    print("DFS 1:")
    dfs_iterative_1(adj_list_2, start_node_2)
    print("\n")

    print("DFS 2:")
    dfs_iterative_2(adj_list_2, start_node_2)
    print("\n")
else:
    print("Skipping generated file test.")
