# -*- coding: utf-8 -*-
"""PE04_202310907_김민주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPK76Oa0zqlHUVY_jHF3Oip_RD-b1i0W
"""

import heapq

class Node:
    def __init__(self, symbol, prob):
        self.symbol = symbol
        self.prob = prob
        self.left = None
        self.right = None

    def __lt__(self, other):
        return self.prob < other.prob

def build_huffman_tree(symbols_probs):
    heap = [Node(sym, prob) for sym, prob in symbols_probs.items()]
    heapq.heapify(heap)

    while len(heap) > 1:
        n1 = heapq.heappop(heap)
        n2 = heapq.heappop(heap)
        new_node = Node(None, n1.prob + n2.prob)
        new_node.left = n1
        new_node.right = n2
        heapq.heappush(heap, new_node)
    return heap[0]

def generate_codes(node, code="", code_dict={}):
    if node is None:
        return
    if node.symbol is not None:
        code_dict[node.symbol] = code
        return
    generate_codes(node.left, code + "0", code_dict)
    generate_codes(node.right, code + "1", code_dict)
    return code_dict

symbols_probs_a = {
    'A': 0.08833, 'B': 0.01267, 'C': 0.02081, 'D': 0.04376,
    'E': 0.14878, 'F': 0.02455, 'G': 0.01521, 'H': 0.05831,
    'I': 0.05644, 'J': 0.00080, 'K': 0.00867, 'L': 0.04124,
    'M': 0.02361
}

symbols_probs_b = {
    'N': 0.06498, 'O': 0.07245, 'P': 0.02575, 'Q': 0.00800,
    'R': 0.06872, 'S': 0.05537, 'T': 0.09351, 'U': 0.02762,
    'V': 0.01160, 'W': 0.01868, 'X': 0.00146, 'Y': 0.01521,
    'Z': 0.00053
}

tree_a = build_huffman_tree(symbols_probs_a)
codes_a = generate_codes(tree_a)

tree_b = build_huffman_tree(symbols_probs_b)
codes_b = generate_codes(tree_b)

print("Huffman codes for a:")
for s, c in sorted(codes_a.items()):
    print(f"{s}: {c}")

print("\nHuffman codes for b:")
for s, c in sorted(codes_b.items()):
    print(f"{s}: {c}")

