# -*- coding: utf-8 -*-
"""pe07_202310907_김민주

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FU_FnZ8KcjkipPD3i8qH_hCuUXvYQZH4
"""

import sys

sys.setrecursionlimit(2000)

def knapsack_memo(P, W, M, n):
    """
    0/1 배낭 문제를 메모이제이션(재귀 + DP)으로 해결합니다.

    :param P: 아이템 가치 리스트 (P[i-1]은 i번째 아이템의 가치)
    :param W: 아이템 무게 리스트 (W[i-1]은 i번째 아이템의 무게)
    :param M: 최대 배낭 용량
    :param n: 아이템의 총 개수
    :return: 최대 가치
    """
    dp = [[-1 for _ in range(M + 1)] for _ in range(n + 1)]

    def solve(index, capacity):
        """
        index: 현재 고려하는 아이템의 인덱스 (1부터 n까지)
        capacity: 현재 남은 배낭 용량
        """
        # 1. Base Case: 모든 아이템을 다 고려했거나 남은 용량이 0인 경우
        if index == 0 or capacity == 0:
            return 0

        # 2. Memoization: 이미 계산된 값이 있으면 반환
        if dp[index][capacity] != -1:
            return dp[index][capacity]

        # 현재 아이템 (P[index-1], W[index-1])
        current_weight = W[index - 1]
        current_value = P[index - 1]

        # 3. Decision: 현재 아이템을 넣을 수 있는 경우 (용량이 충분)
        if current_weight <= capacity:

            # (1) 현재 아이템을 포함하는 경우:
            #     현재 가치 + (남은 용량 - 현재 무게)로 다음 아이템(index-1)을 고려한 최대 가치
            value_with_item = current_value + solve(index - 1, capacity - current_weight)

            # (2) 현재 아이템을 포함하지 않는 경우:
            #     용량은 그대로, 다음 아이템(index-1)을 고려한 최대 가치
            value_without_item = solve(index - 1, capacity)

            # 두 경우 중 최대 가치를 저장
            result = max(value_with_item, value_without_item)

        # 4. Decision: 현재 아이템을 넣을 수 없는 경우 (용량이 부족)
        else:
            # 현재 아이템을 포함하지 않음. 용량은 그대로, 다음 아이템(index-1)을 고려
            result = solve(index - 1, capacity)

        # 5. Store result (Memoization)
        dp[index][capacity] = result
        return result

    # n번째 아이템까지 고려하고, 최대 용량 M을 사용했을 때의 최대 가치를 계산
    return solve(n, M)

# --- 예제 실행 ---
n = 6
M = 100
P = [40, 35, 18, 4, 10, 2]  # p1, p2, p3, p4, p5, p6
W = [100, 50, 45, 20, 10, 5] # w1, w2, w3, w4, w5, w6

max_value = knapsack_memo(P, W, M, n)

print(f"아이템 수 (n): {n}")
print(f"최대 배낭 용량 (M): {M}")
print(f"아이템 가치 (P): {P}")
print(f"아이템 무게 (W): {W}")
print("-" * 30)
print(f"메모이제이션을 통해 얻을 수 있는 최대 가치: {max_value}")