# -*- coding: utf-8 -*-
"""PE02_202310907_김민주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RS6B-uVGDJ9ZyludvkzymUlzdimfoV6H
"""

import sys
import os
import random

sys.setrecursionlimit(2000)

def kosaraju(graph, n):
    # Step 1: First DFS on the original graph
    visited = [False] * (n + 1)
    stack = []

    def dfs1(u):
        visited[u] = True
        for v in graph.get(u, []):
            if not visited[v]:
                dfs1(v)
        stack.append(u)

    for i in range(1, n + 1):
        if not visited[i] and i in graph:
            dfs1(i)

    # Step 2: Create the transpose graph
    transpose_graph = {i: [] for i in range(1, n + 1)}
    for u in graph:
        for v in graph[u]:
            transpose_graph.setdefault(v, []).append(u)

    # Step 3: Second DFS on the transpose graph
    visited = [False] * (n + 1)
    sccs = []

    def dfs2(u, current_scc):
        visited[u] = True
        current_scc.append(u)
        for v in transpose_graph.get(u, []):
            if not visited[v]:
                dfs2(v, current_scc)

    while stack:
        u = stack.pop()
        if not visited[u]:
            current_scc = []
            dfs2(u, current_scc)
            sccs.append(current_scc)

    return sccs

def read_graph_from_file(filename):
    graph = {}
    max_node = 0
    try:
        with open(filename, 'r') as f:
            for line in f:
                if line.strip():
                    u, v = map(int, line.strip().split())
                    graph.setdefault(u, []).append(v)
                    max_node = max(max_node, u, v)
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return None, None
    return graph, max_node

def generate_random_graph(num_vertices, num_edges):
    graph_data = []
    max_node = num_vertices
    for _ in range(num_edges):
        u = random.randint(1, num_vertices)
        v = random.randint(1, num_vertices)
        graph_data.append((u, v))
    return graph_data, max_node

filename = "searchgraph.txt"
if os.path.exists(filename):
    graph, n = read_graph_from_file(filename)
    if graph:
        sccs = kosaraju(graph, n)
        for i, scc in enumerate(sccs, 1):
            print(f"SCC {i}: {scc}")
else:
    print(f"File '{filename}' not found.")

print("-" * 30)

num_vertices = 15
num_edges = 30
print(f"Generating a random graph.")

generated_data, n_gen = generate_random_graph(num_vertices, num_edges)
graph_gen = {}
for u, v in generated_data:
    graph_gen.setdefault(u, []).append(v)

sccs_gen = kosaraju(graph_gen, n_gen)
for i, scc in enumerate(sccs_gen, 1):
    print(f"SCC {i}: {scc}")