# -*- coding: utf-8 -*-
"""PE03_202310907_김민주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2RcSXXpy-SG-4U0nSYaKrS7ZZCwa1OL
"""

# 그래프 정의 (가중치 인접 리스트)
graph = {
    1: [(2, 50), (4, 10)],
    2: [(3, 10), (4, 20), (5, 20)],
    3: [(1, 45)],
    4: [(2, 15), (5, 15)],
    5: [(3, 15), (6, 3)],
    6: [],
}
nodes = list(graph.keys())

import heapq

def dijkstra(graph, start_node):
    distances = {node: float('inf') for node in graph}
    distances[start_node] = 0
    priority_queue = [(0, start_node)]

    while priority_queue:
        current_distance, current_node = heapq.heappop(priority_queue)

        if current_distance > distances[current_node]:
            continue

        if current_node in graph:
            for neighbor, weight in graph[current_node]:
                new_distance = current_distance + weight

                if new_distance < distances[neighbor]:
                    distances[neighbor] = new_distance
                    heapq.heappush(priority_queue, (new_distance, neighbor))

    return distances

start_node = 1

# 다익스트라 알고리즘 실행
shortest_distances = dijkstra(graph, start_node)

# 결과 출력
print(f"시작 노드 {start_node}로부터의 최단 거리:")
for node, distance in sorted(shortest_distances.items()):
    if distance == float('inf'):
        print(f"노드 {node}: 도달 불가능 (inf)")
    else:
        print(f"노드 {node}: {distance}")