# -*- coding: utf-8 -*-
"""pe05_202310907_김민주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFpIBm1OwSgtHa1bEGBdcdPchVfLhmgM
"""

# Union-Find 클래스 (Disjoint Set)
class UnionFind:
    def __init__(self, vertices):
        self.parent = {v: v for v in vertices}
        self.size = {v: 1 for v in vertices}

    def find(self, i):
        if self.parent[i] == i:
            return i
        self.parent[i] = self.find(self.parent[i])
        return self.parent[i]

    def union(self, i, j):
        root_i = self.find(i)
        root_j = self.find(j)

        if root_i != root_j:
            if self.size[root_i] < self.size[root_j]:
                self.parent[root_i] = root_j
                self.size[root_j] += self.size[root_i]
            else:
                self.parent[root_j] = root_i
                self.size[root_i] += self.size[root_j]
            return True
        return False

def kruskal(vertices, edges):
    edges.sort(key=lambda item: item[2])

    uf = UnionFind(vertices)

    mst_edges = []
    min_cost = 0
    num_vertices = len(vertices)

    for u, v, weight in edges:
        if len(mst_edges) == num_vertices - 1:
            break

        if uf.find(u) != uf.find(v):
            uf.union(u, v)
            mst_edges.append((u, v, weight))
            min_cost += weight

    return mst_edges, min_cost

vertices = ['A', 'B', 'C', 'D', 'E']
edges = [
    ('A', 'B', 4), ('A', 'C', 2), ('B', 'C', 1),
    ('B', 'D', 2), ('B', 'E', 3), ('C', 'D', 4),
    ('C', 'E', 5), ('D', 'E', 1)
]

# 크루스칼 알고리즘 실행
mst, cost = kruskal(vertices, edges)

# 결과 출력
print("최소 신장 트리 (MST) 간선:")
for u, v, w in mst:
    print(f"  {u} - {v} (가중치: {w})")
print("-" * 30)
print(f"최소 비용: {cost}")