# -*- coding: utf-8 -*-
"""pe06_202310907_김민주.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0peFNmXdKXtQyk9VFAltZVeFlOdSuK0
"""

import heapq

def prim(graph, start_node):

    # MST에 포함된 정점을 기록
    visited = set()
    min_heap = [(0, start_node)]

    total_weight = 0
    mst_edges = []

    while min_heap:
        # 힙에서 가장 작은 가중치 간선 정보를 추출 (O(log V))
        weight, current_node = heapq.heappop(min_heap)

        # 이미 MST에 포함된 정점이면 건너뜀
        if current_node in visited:
            continue

        # 현재 정점을 MST에 추가
        visited.add(current_node)
        total_weight += weight

        if weight > 0 or current_node != start_node:
             pass

        # 현재 정점과 연결된 모든 이웃을 탐색
        for neighbor_weight, neighbor in graph.get(current_node, []):
            if neighbor not in visited:
                heapq.heappush(min_heap, (neighbor_weight, neighbor))

    return total_weight

# --- 그래프 정의 ---

# 1. 왼쪽 그래프 (6개 정점)
graph1 = {
    1: [(10, 2), (30, 4), (45, 5)],
    2: [(10, 1), (50, 3), (40, 5), (25, 6)],
    3: [(50, 2), (35, 5), (15, 6)],
    4: [(30, 1), (20, 6)],
    5: [(45, 1), (40, 2), (35, 3), (55, 6)],
    6: [(25, 2), (15, 3), (20, 4), (55, 5)]
}

# 2. 오른쪽 그래프 (6개 정점)
graph2 = {
    1: [(16, 2), (19, 5), (21, 6)],
    2: [(16, 1), (5, 3), (6, 4), (11, 6)],
    3: [(5, 2), (10, 4)],
    4: [(6, 2), (10, 3), (14, 6), (18, 5)],
    5: [(19, 1), (33, 6), (18, 4)],
    6: [(21, 1), (11, 2), (14, 4), (33, 5)]
}

# --- 실행 및 결과 ---

print("Prim 알고리즘 실행 결과")
print("---")

# 그래프 1 실행 (시작 정점 1)
mst_weight_1 = prim(graph1, 1)
print(f"MST 총 가중치1 (시작 정점 1): {mst_weight_1}")

# 그래프 2 실행 (시작 정점 1)
mst_weight_2 = prim(graph2, 1)
print(f"MST 총 가중치2 (시작 정점 1): {mst_weight_2}")